### ISSUE TITLE
Absolute URL of image

### ISSUE THREAD

**Issue by MartinKokesCz** [geniv/nette-thumbnail#4]
Hello, guys, how can i get full URL with baseUrl please? 

For example **http://localhost/images/image-sfdsoi848941316.jpg** instead of **www/images/image-sfdsoi848941316.jpg**

btw. Thank you for an awesome extension :-)

**Comment by geniv** [comment]
super, jsem moc rad ze se ti rozsireni libi!

co se tyce reseni pro absolutni cestu tak to bylo zamerne delany aby to vracelo bez baseUrl, takze se to ve vysledku resilo stylem ze se vzalo src="{$baseUrl}{$thubnailer...}", a nebo se pouziva `<baseurl>` jako html direktiva.

Eventualne pokud chces klidne navrhni PR, a rad to tam namerguju, co se koukam do kodu tak to v tuto chvilu neni uplne kompabibilni s NW 3.x pokud vyuzivas nejposlednejsi verzi

**Comment by MartinKokesCz** [comment]
Posílám pull request #5 přidal jsem tam zatím jen parametr pro full Url. Kompatibilitu s Nette 3.x jsem zatím neřešil.
